import { ActionIcon, Box, Button, Text, TextInput } from "@mantine/core";
import { IconArrowRight, IconSearch } from "@tabler/icons-react";
import Head from "next/head";
import Image from "next/image";
import styles from "./page.module.css";
import { useEffect, useState } from "react";
import Link from "next/link";
import MapComponent from "@/components/Map";

export default function Page() {
    const [categories, setCategories] = useState([]);

    useEffect(() => {
        const getCategories = async () => {
            const response = await fetch(
                "http://128.189.194.203:5206/api/categories",
                { method: "GET", credentials: "include" }
            );

            const data = await response.json();

            setCategories(data);

            // console.log(await response.json());
        };

        getCategories();
    }, []);

    return (
        <div className={styles.layoutStyle}>
            <Box>
                <Head>
                    <title>LocalCompass</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <div className={styles.logo}>
                    <Image
                        src={"./logo.svg"}
                        width={200}
                        height={200}
                        alt={"local compass logo"}
                    />
                </div>

                <div className={styles.headerFontLayout}>
                    <Text>
                        <b>LocalCompass, </b>Conscious Consumption is One-Click
                        Away
                    </Text>
                </div>

                <div id={"map"} style={{ height: "200px" }}></div>

                <div className={styles.searchBarContainer}>
                    <TextInput
                        className={styles.searchBarStyle}
                        size="md"
                        placeholder="Search location..."
                        rightSectionWidth={45}
                        leftSection={<IconSearch stroke={1.5} />}
                        rightSection={
                            <ActionIcon
                                style={{
                                    backgroundColor: "rgb(173, 173, 215)",
                                }}
                                size={32}
                                radius="xl"
                                variant="filled"
                            >
                                <IconArrowRight stroke={1.5} />
                            </ActionIcon>
                        }
                    />
                </div>

                <div className={styles.buttonFrame}>
                    <div className={styles.layout}>
                        {categories &&
                            categories.map(
                                ({
                                    id,
                                    categoryName,
                                }: {
                                    id: string;
                                    categoryName: string;
                                }) => (
                                    <Button
                                        key={id}
                                        className={styles.buttonStyle}
                                        component={Link}
                                        href={`/categories/${id}`}
                                    >
                                        {categoryName}
                                    </Button>
                                )
                            )}
                    </div>
                </div>

                <div className={styles.searchDescriptionFontLayout}>
                    <Text>
                        LocalCompass uplifts the community by supporting small,
                        locally owned BIPOC and LGBTQ+ businesses.
                    </Text>
                    <Text>
                        Join us in celebrating the diversity that makes our
                        community thrive.
                    </Text>
                </div>
            </Box>
        </div>
    );
}
